#!/usr/bin/env node
// Generate spelling-game/js/fry.js from the committed word lists.
//
// WHY A GENERATOR AND NOT A HAND-WRITTEN ARRAY. The old FRY array was written
// from memory and said so; measured against a sourced list its exact ranks
// agreed 6% of the time. Generating it from `data/fry-1000.txt` means the
// ordering has one origin, it is diffable, and nobody is ever tempted to
// "just add a word" in the middle and shift 700 ranks by hand.
//
// WHY THE OUTPUT IS COMMITTED JAVASCRIPT AND NOT READ AT RUNTIME. spine.js is
// an ES module the browser imports directly. There is no build step in this
// project and there should not be one for a kid's game that has to keep working
// after a year of nobody touching it — so the generated module is checked in and
// the game imports it like any other file. The .txt is the source of truth; this
// script is how it reaches the browser.
//
// Re-run after editing data/fry-1000.txt or data/dolch.txt:
//   node tools/build-fry.js

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { resolve, dirname, join } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(HERE, '..');
const GAME = join(REPO_ROOT, 'spelling-game');

/** The spine's word contract: lowercase a-z, nothing else. */
const TYPABLE = /^[a-z]+$/;

function lines(path) {
  return readFileSync(path, 'utf8')
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line !== '');
}

const ordered = lines(join(GAME, 'data', 'fry-1000.txt'));
const dolch = new Set(lines(join(GAME, 'data', 'dolch.txt')));

// Rank is the position in the PUBLISHED list, kept even for words we drop, so
// `band` stays comparable to anyone else's copy of Fry. Dropping `America` must
// not shift every word after it into the wrong hundred.
const kept = [];
const dropped = [];
ordered.forEach((word, index) => {
  const rank = index + 1;
  if (TYPABLE.test(word)) {
    kept.push({ word, rank, dolch: dolch.has(word) });
  } else {
    dropped.push(word);
  }
});

const rows = kept
  .map(({ word, rank, dolch: isDolch }) => `  ['${word}', ${rank}, ${isDolch}],`)
  .join('\n');

const output = `// GENERATED BY tools/build-fry.js — DO NOT EDIT BY HAND.
//
// Source of truth: spelling-game/data/fry-1000.txt (order) and
// spelling-game/data/dolch.txt (membership). Edit those and re-run:
//
//   node tools/build-fry.js
//
// Fry's 1000 most frequent English words, in published rank order. Public
// domain, which is why the list travels with the repo — the same licence line
// the spec draws against the gitignored Merriam-Webster cache.
//
// EACH ENTRY CARRIES ITS PUBLISHED RANK rather than relying on array position.
// ${dropped.length} words are dropped here because the engine accepts a-z only and
// cannot type them — contractions and proper nouns — and dropping them must not
// shift everything after them into the wrong hundred. \`band\` is
// \`ceil(rank / 100)\` and is the load-bearing number: measured against an
// independently-written list, exact ranks agreed 6% of the time and bands agreed
// 98%. Band is signal; position inside it is noise. Do not sort by array index.
//
// Dropped: ${dropped.join(' ')}

/** @type {[string, number, boolean][]} word, published Fry rank, is a Dolch sight word */
export const FRY = [
${rows}
];
`;

const target = join(GAME, 'js', 'fry.js');
writeFileSync(target, output);
process.stdout.write(
  `wrote ${target}\n` +
    `  ${kept.length} words kept of ${ordered.length}\n` +
    `  ${dropped.length} dropped (not a-z): ${dropped.join(' ')}\n` +
    `  ${kept.filter((e) => e.dolch).length} flagged as Dolch\n`,
);
